import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repositoryRoot = resolve(fileURLToPath(new URL('..', import.meta.url)));
const siteRoot = resolve(repositoryRoot, 'dist/site');
const index = await readFile(resolve(siteRoot, 'index.html'), 'utf8');
const assets = [...index.matchAll(/(?:src|href)="(\/assets\/[^\"]+)"/g)].map((match) => match[1]);
const shell = [...new Set([
  '/',
  '/folder-mark.svg',
  '/archive-room.webp',
  '/legal.css',
  '/privacy/',
  '/terms/',
  ...assets,
])].sort();

function fileForUrl(url) {
  if (url === '/') return 'index.html';
  if (url.endsWith('/')) return `${url.slice(1)}index.html`;
  return url.slice(1);
}

const revision = createHash('sha256');
for (const url of shell) {
  revision.update(url);
  revision.update(await readFile(resolve(siteRoot, fileForUrl(url))));
}
const cacheName = `folder-recipe-${revision.digest('hex').slice(0, 16)}`;

const worker = `/* Generated by scripts/build-site.mjs. Do not edit this file directly. */
const CACHE_PREFIX = 'folder-recipe-';
const CACHE = '${cacheName}';
const SHELL = ${JSON.stringify(shell)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(SHELL)));
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys
      .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE)
      .map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

async function networkFirstNavigation(request) {
  try {
    return await fetch(request);
  } catch {
    return (await caches.match(request)) || (await caches.match('/')) || Response.error();
  }
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  if (request.mode === 'navigate') {
    event.respondWith(networkFirstNavigation(request));
    return;
  }
  event.respondWith(caches.match(request).then((cached) => cached || fetch(request)));
});
`;

await writeFile(resolve(siteRoot, 'sw.js'), worker);
